### Register
POST http://localhost:8080/api/auth/public/register
Content-Type: application/json

{
  "username": "prakhar",
  "email": "prakhar@test.com",
  "password": "1234"
}

### Login
POST http://localhost:8080/api/auth/public/login
Content-Type: application/json

{
  "username": "prakhar",
  "password": "1234"
}